replicaCount: 1

image:
  repository: steevan1/go-web-app
  pullPolicy: IfNotPresent
  tag: "10016307834"

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

httpRoute:
  enabled: false

autoscaling:
  enabled: false        # set to true if you want HPA
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
